### ISSUE TITLE
Add support for component 

### ISSUE THREAD

**Issue by mdhsl** [mdhsl/SMLEditor#22]

**Comment by mikebotts** [comment]
For now, a component should just show name and xlink:title (in parenthesis), but the name should be a hyperlink that links to the xlink:href :
Not finished yet:

[MVCO_Workhorse](http://www.sensorML.com/2.0/mvco/sensor/MVCO_Workhorse_1200.xml) (urn:whoi:mvco:workhorse_1200)

**Comment by mdhsl** [comment]
I know, but it is dupplicated. The other one is still tagged as enhancement/bug #issue10

**Comment by mdhsl** [comment]
See #10
