### ISSUE TITLE
Add support for ConnectionList 

### ISSUE THREAD

**Issue by mdhsl** [mdhsl/SMLEditor#24]

**Comment by mikebotts** [comment]
For now:
- Show "Connection List" as a top level subject title like "Capabilities" and "Characteristics"
- Then just indent and list the connections simply as source + arrowIcon + destination, e.g.
  
  this/inputs/seaWaterPressure  ——>  MVCO_Workhorse/inputs/seaWaterPressure

**Comment by mdhsl** [comment]
Done
