### ISSUE TITLE
Switch Axes on plots

### ISSUE THREAD

**Issue by mikebotts** [mdhsl/SMLEditor#30]
When plotting from a data array, the first field of the DataRecord should be plotted as x, the second as y, and the third if it exist as z. The plot on the Gamma_2070 is reversed and thus looks funny.

**Comment by mikebotts** [comment]
Just to clarify, x should be horizontal, y vertical.

**Comment by mdhsl** [comment]
Ok. Done, but the davis 7817 graph is not corresponding anymore. See 
[ext_temp_sensor_std.pdf](https://github.com/mdhsl/SMLEditor/files/160619/ext_temp_sensor_std.pdf)
